"""empty message

Revision ID: 03af97794104
Revises: cb51c4fe89bd
Create Date: 2025-11-21 19:56:46.920622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03af97794104'
down_revision = 'cb51c4fe89bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('category', sa.String(length=20), nullable=True))
    op.execute("UPDATE post SET category = 'unknown' WHERE category IS NULL")
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('category', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
