"""Add type column to Post model

Revision ID: e9e1ff2a2ea8
Revises: c20f483f29a6
Create Date: 2025-11-20 22:18:57.020278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9e1ff2a2ea8'
down_revision = 'c20f483f29a6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.alter_column('status',
                              existing_type=sa.VARCHAR(length=12),
                              type_=sa.String(length=20),
                              existing_nullable=True)
        batch_op.alter_column('type',
                              existing_type=sa.VARCHAR(length=10),
                              type_=sa.String(length=20),
                              existing_nullable=False)
        batch_op.drop_column('media_urls')
    op.execute("UPDATE post SET category = 'unknown' WHERE category IS NULL")
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('category', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_urls', postgresql.JSON(
            astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', postgresql.ENUM(
            'FOOD_DONATIONS', 'ANIMAL_SHELTER', 'HONEY_DOS', name='postcategory'), autoincrement=False, nullable=False))
        batch_op.alter_column('type',
                              existing_type=sa.String(length=20),
                              type_=sa.VARCHAR(length=10),
                              existing_nullable=False)
        batch_op.alter_column('status',
                              existing_type=sa.String(length=20),
                              type_=sa.VARCHAR(length=12),
                              existing_nullable=False)

    # ### end Alembic commands ###
